version: '3.8'
services:
  spring-boot-server:
    build:
      context: .
      dockerfile: spring-boot-server/Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/nom_de_la_bdd?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: utilisateur_mysql
      SPRING_DATASOURCE_PASSWORD: mot_de_passe_mysql
    depends_on:
      - mysql

  angular-client:
    build:
      context: .
      dockerfile: angular-15-client/Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - spring-boot-server

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: nom_de_la_bdd
      MYSQL_USER: utilisateur_mysql
      MYSQL_PASSWORD: mot_de_passe_mysql
      MYSQL_ROOT_PASSWORD: mot_de_passe_root
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
